[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["nodemailer"]
  directory = "netlify/functions"
  included_files = ["netlify/functions/scheduled-digest.js"]

[functions.scheduled-digest]
  schedule = "0 0 1 * *"

[dev]
  framework = "vite"
  targetPort = 3001
  port = 8888
  functionsPort = 9999
  command = "npm run dev"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Add this new redirect rule for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"